// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...


// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX57PdC30BgIGgx8pnIFtepeYD9u17mQk',
    appId: '1:660448644166:web:f0b211abce83f4a095ce47',
    messagingSenderId: '660448644166',
    projectId: 'otizmdestek',
    authDomain: 'otizmdestek.firebaseapp.com',
    storageBucket: 'otizmdestek.appspot.com',
    measurementId: 'G-W70MLNGLGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-KF_nVwZswR8LXr2Hxjr0GCXJMKANeiE',
    appId: '1:660448644166:android:0052814c47281d0795ce47',
    messagingSenderId: '660448644166',
    projectId: 'otizmdestek',
    storageBucket: 'otizmdestek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhCW60yynrcmoBbcPcIrvVmuMqGrWNoVQ',
    appId: '1:660448644166:ios:a35e85d9ff01ffaf95ce47',
    messagingSenderId: '660448644166',
    projectId: 'otizmdestek',
    storageBucket: 'otizmdestek.appspot.com',
    iosBundleId: 'com.example.otizmDestekVeBilgiAgi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhCW60yynrcmoBbcPcIrvVmuMqGrWNoVQ',
    appId: '1:660448644166:ios:a35e85d9ff01ffaf95ce47',
    messagingSenderId: '660448644166',
    projectId: 'otizmdestek',
    storageBucket: 'otizmdestek.appspot.com',
    iosBundleId: 'com.example.otizmDestekVeBilgiAgi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX57PdC30BgIGgx8pnIFtepeYD9u17mQk',
    appId: '1:660448644166:web:faa60ee23237209295ce47',
    messagingSenderId: '660448644166',
    projectId: 'otizmdestek',
    authDomain: 'otizmdestek.firebaseapp.com',
    storageBucket: 'otizmdestek.appspot.com',
    measurementId: 'G-TLKFQ0KTRZ',
  );
}
